/// String literals can be preceeded by any of b, r, u, f, rb, rf in Python
/// so this enum tracks which flag (if any) is present on the string.
#[derive(Debug, PartialEq, Eq, Hash)]
pub enum StringFlag {
    B,
    R,
    U,
    F,
    Rb,
    Rf,
}

#[derive(Debug, PartialEq, Eq, Hash)]
pub enum NumberBase {
    Decimal,
    Hexadecimal,
    Octal,
    Binary,
}

#[derive(Debug, PartialEq, Eq, Hash)]
pub enum Token {
    EndMarker,
    Name(String),
    Number(String, NumberBase),
    String(String, Option<StringFlag>),
    Newline,
    Indent,
    Dedent,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Colon,
    Comma,
    Semi,
    Plus,
    Minus,
    Star,
    Slash,
    VBar,
    Amper,
    Less,
    Greater,
    Equal,
    Dot,
    Percent,
    LBrace,
    RBrace,
    EqEqual,
    NotEqual,
    LessEqual,
    GreaterEqual,
    Tilde,
    Circumflex,
    LeftShift,
    RightShift,
    DoubleStar,
    PlusEqual,
    MinEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    AmperEqual,
    VBarEqual,
    CircumFlexEqual,
    LeftShiftEqual,
    RightShiftEqual,
    DoubleStarEqual,
    DoubleSlash,
    DoubleSlashEqual,
    At,
    AtEqual,
    RArrow,
    Ellipsis,
    Op(String),
    ErrorToken(String),
    Comment(String),
}
