[package]
name = "reticulated"
version = "0.1.0"
authors = ["Creston Bunch <crestonbunch@gmail.com>"]
edition = "2018"

[dependencies]
lexer = { path = "./lexer" }
parser = { path = "./parser" }

[workspace]
members = [
    "lexer",
    "parser",
    "compiler"
]
