[package]
name = "metagrammar"
version = "0.1.0"
authors = ["Creston Bunch <crestonbunch@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.32"
quote = "0.6"
proc-macro2 = { version = "0.4"}
lexer = { path = "../../lexer" }
